spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    password: '1234'

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

jwt:
  expired:
    access: '10000000'
    refresh: '100000000'
  secret: SECRETKEYTEST1234567890TEST!@#$%^&
map:
  naver:
    apikey: b2a72569-9548-4d0d-bd01-8fca5d2740df

