spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    password: '1234'

  redis:
    host: 127.0.0.1
    port: 55000
    password: redispw

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'false'
        create_empty_composites:
          enabled: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 6000
            readTimeout: 6000
            loggerLevel: basic

jwt:
  expired:
    access: '1000000'
    refresh: '10000000'
  secret: SECRETKEYTEST1234567890TEST!@#$%^&
map:
  naver:
    apikey: b2a72569-9548-4d0d-bd01-8fca5d2740df

